name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}

    - name: Set up npm authentication
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Run Release Script
      run: bun release.ts
