name: Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  release:
    runs-on: ubuntu-latest'
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Set up npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Set up Git for pushing
        run: |
          git config user.name "brandon-schabel"
          git config user.email "brandonschabel1995@gmail.com"
          git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }}@github.com/brandon-schabel/u-tools.git

      - name: Ensure no git lock before release
        run: rm -f .git/index.lock

      - name: Run Release Script
        run: bun release.ts